version: '3.7'
services:
  bd:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_DB: alfa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

  service:
    image: burlakovem/alfa-2
    ports:
    - 8081:8080
    depends_on:
      - bd
